name: Build Wheels

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64
            os: windows-latest
            cibw_archs: "x86_64"

          - name: macOS ARM64
            os: macos-latest
            cibw_archs: "arm64"

          - name: Linux x86_64
            os: ubuntu-latest
            cibw_archs: "x86_64"

          - name: Linux aarch64
            os: ubuntu-latest
            cibw_archs: "aarch64"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up QEMU
        if: matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.0
        env:
          # 只编译 3.10 及以上版本
          CIBW_SKIP: "cp36-* cp37-* cp38-* cp39-* pp* *-musllinux*"
          CIBW_ARCHS: "${{ matrix.cibw_archs }}"
          CIBW_BUILD_VERBOSITY: 1
          
          # 针对 C++23 的 Linux 镜像设置
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28

          # 只有 Linux 需要安装 git
          CIBW_BEFORE_ALL_LINUX: dnf install -y git || yum install -y git

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.name }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

      - name: Upload Release Assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: wheelhouse/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
